// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default']
    ILaLanguage: typeof import('~icons/la/language')['default']
    IMdiContentDuplicate: typeof import('~icons/mdi/content-duplicate')['default']
    IMdiHomeSearchOutline: typeof import('~icons/mdi/home-search-outline')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    IRiArticleLine: typeof import('~icons/ri/article-line')['default']
    Register: typeof import('./components/register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}

export {}
